packages:
  - 'packages/*'
  - 'examples/*'
allowBuilds:
  '@biomejs/biome': true
  esbuild: true
  better-sqlite3: true
  '@parcel/watcher': false # via ng-packagr > sass
  lmdb: false # via @angular/build
  msgpackr-extract: false
packageExtensions:
  '@analogjs/vite-plugin-angular':
    peerDependencies:
      typescript: '*'
